### ISSUE TITLE
Product

### ISSUE THREAD

**Issue by miw-upm** [miw-upm/SPRING.tpv#10]
### Gestor de productos

- Permitir la creación, lectura, modificación de productos. Se debe realizar en sus tres variantes: Artículos y servicios de Bordados o Prenda Impresa. La lectura debe ser sencilla, sin búsquedas, mostrando una lista de todos los productos

- No se permite el borrado, solo descatalogarlo. Aunque se debe incluir en el borrado de las BD para cuestiones de test

> Tiempo estimado: **10h**. Tiempo real: **14h 5min**

[Wiki](url)

**Comment by JaviKx2** [comment]
¿Se entiende la descatalogación de un producto como la modificación del atributo en cuestión? (Petición PUT/PATCH)
