### ISSUE TITLE
API Resources for Customers

### ISSUE THREAD

**Issue by fclopezjurado** [miw-upm/SPRING.tpv#33]
Implementación de los endpoints en la API de la aplicación, para la creación y el listado de clientes.

- **_GET /customers_**: devuelve el listado de clientes paginados. Se mandan los datos de la paginación por atributos (tamaño de página y número de página).
- **_GET /customers/mobile/{mobile}_**: devuelve la información de un único cliente, utilizando su número de móvil para realizar la búsqueda.
- **_GET /customers/identification/{identification}_**: devuelve la información de un único cliente, utilizando su DNI para realizar la búsqueda.
- **_GET /customers/email/{email}_**: devuelve la información de un único cliente, utilizando su email para realizar la búsqueda.
- **_POST /customers_**: Creación de un cliente. Se enviarán los siguientes datos:

  * Móvil
  * Nombre
  * Contraseña
  * Dirección
  * Identificación
  * Si está activo o no

Además, es necesario definir el correspondiente wrapper.
Todos los endpoints solo pueden ser utilizados por un **_usuario logueado_** con el rol **_ADMIN_**. En caso de no existir el recurso o no poder proporcionarlo, deben retornar un error HTTP.

Se recomienda la utilización de [Swagger](http://swagger.io/) para la documentación de la API.

> Tiempo estimado: **??h**. Tiempo real: **??h**

[Wiki](url)

**Comment by fclopezjurado** [comment]
@EduardoFrancoGutierrez artista! cuando puedas hablamos de los endpoints de este ticket y de los tickets #34 y #35 porque lo mismo le damos una vuelta a la definición y nos podemos ahorrar recursos.

He estado pensando, que lo mismo podríamos reducir los endpoints de los 3 tickets a solo 2.

**_GET /users_** que devuelva info de clientes, managers u operadores, en función de un rol proporcionado como @QueryParameter y los filtros de móvil, email, etc. también como @QueryParameter.

**_POST /users_** que permita crear clientes, managers y operadores, en función de los parámetros proporcionados en el @RequestBody. También se puede incluir el rol del futuro usuario y así es menos curro.

Se nos quedaría en dos endpoints, algo más currados.

Dale una vuelta y cuando puedas avísame y lo ajustamos ;-)

**Comment by EduardoFrancoGutierrez** [comment]
Hola @fclopezjurado, efectivamente como tal y como acordamos el viernes, voy a refacotorizar el codigo y crear una nueva issue para dejarlo tal y como comentas. Lo más seguro que para este sabado o domigo como maximo ya este refactorizado puesto los apis de esa manera :)!!

PD: En relacion a la especificación de las urls y los parametros es como comentas, aun asi cuando me ponga a definir las urls nuevas paras las api te lo comento. En relacion al paso de parametros lo tenia pensando de esa manera.

**Comment by EduardoFrancoGutierrez** [comment]
Por cierto @fclopezjurado voy a cerrar estas issues ya ;)!!
