### ISSUE TITLE
Product update: image

### ISSUE THREAD

**Issue by sergiobanegas** [miw-upm/SPRING.tpv#39]
Añadir un campo imagen (tipo String) a la entidad producto que almacene la URL de su imagen. 
Se deberá de crear una carpeta donde se almacenen las imágenes y añadir en ella unas cuantas fotos para poder incluir su URL en el poblador de productos.

> Tiempo estimado: **??h**. Tiempo real: **??h**

[Wiki](url)

**Comment by TamaraJDz** [comment]
Hola @sergiobanegas , entiendo que la imagen no es obligatoria, con lo cual, no lo meto en el constructor, si me equivoco me dices.

**Comment by sergiobanegas** [comment]
@TamaraJDz : Lo veo correcto que no sea obligatoria, está perfecto así 👍
