### ISSUE TITLE
Voucher

### ISSUE THREAD

**Issue by miw-upm** [miw-upm/SPRING.tpv#5]
### Gestión de vales
- Permitir la creación, lectura y consumos de vales (asegurándose que sea válido). No se debe permitir el borrado de vales.

- Permitir realizar consultas de vales. Se debe ofrecer saber el total de dinero en vales activos.

> Tiempo estimado: **5h**. Tiempo real: **20h**

[Wiki](url)

**Comment by JaviKx2** [comment]
¿Bajo que petición sobre qué URI debería entregarse el total de dinero de vales activos?
Entiendo que la consulta de un vale es devolver ese vale que se pide. Pero no añadir el total junto a ese vale.
