### ISSUE TITLE
Refactorizacion de APIS en relacion a los usuarios

### ISSUE THREAD

**Issue by EduardoFrancoGutierrez** [miw-upm/SPRING.tpv#55]
Refactorización de los endpoints en la API de la aplicación, en relacion a los usuarios. Ahora mismo convive cuatro APIS (customer,manager,operator y user) cuya funcionalidad es practicamente la misma. La idea es que quede solo una API para realizar todas las operativas necesarias para los usuarios.El resultado seria el siguiente:

GET /users que devuelva info de clientes, managers u operadores, en función de un rol proporcionado como @queryparameter y los filtros de móvil, email, etc. también como @queryparameter.

POST /users que permita crear clientes, managers y operadores, en función de los parámetros proporcionados en el @requestbody. También se puede incluir el rol del futuro usuario.

**Comment by fclopezjurado** [comment]
@EduardoFrancoGutierrez Mañana por la tarde, me siento en un momento y detallo todo lo que pueda las definiciones en este ticket, en función de lo que ya tenemos montado ;-)

Nombres de parámetros, de atributos del wrapper, porque también tendremos que ampliar los wrappers, que también les faltan cosillas.

**Comment by fclopezjurado** [comment]
Le he estado echando un ojo al código y yo lo que haría sería lo siguiente.

- Implementar los dos endpoints en la clase [UserResource](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/UserResource.java) de la API, eliminando los recursos que tenemos en [CustomersResource](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/CustomerResource.java), [ManagersResource](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/ManagersResource.java) y [OperatorsResource](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/OperatorsResource.java)

- El wrapper [UserWrapper](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/wrappers/UserWrapper.java) no hace falta tocarlo. Tal y como lo has ampliado está perfecto. Tiene los nombres exactamente iguales a los campos en BD y los que tenemos en front. Aunque para lo que queremos hacer, tendríamos que meter un atributos más, con el ROL asociado al usuario. Te lo explico más abajo en el endpoint de creación.

- Los dos endpoints deben tener la anotación _**@PreAuthorize("hasRole('ADMIN')")**_ que has puesto genial en los que ya has hecho. Las dejamos comentadas si quieres en primera versión, aunque no sería problema, porque en todas las llamadas ya estoy pasando la cabecera. Lo dejo a tu elección.

- Genial si tienen paginación en back-end. En front ya sabes que tienen paginación.

Respecto a los endpoints:

- _**GET /users**_  devuelve un conjunto de usuarios (clientes, gestores, operadores, etcétera) con paginación. Vamos a utilizar la notación _**@QueryParameter**_ para proporcionar filtros y reducir el conjunto de resultados. Los filtros pueden ser los siguientes:

1. _**role**_. string con el nombre del ROL, tal y como están definidos en el enumerado [Role](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/entities/users/Role.java), para filtrar los usuarios por rol. Un ejemplo podría ser `/users?role=ADMIN`

2.  _**mobile**_. int con el número de móvil de un usuario, para filtrar los usuarios por número de móvil. Como el móvil es único, es razonable que solo retorna la información de un usuario o de ninguno. Un ejemplo podría ser `/users?mobile=ADMIN&mobile=666666661`

3.  _**dni**_. string con el DNI de un usuario, para filtrar los usuarios por DNI. Como el DNI es único, en teoría... es razonable que solo retorna la información de un usuario o de ninguno. Un ejemplo podría ser `/users?mobile=ADMIN&dni=52784891D`

4.  _**email**_. string con el correo de un usuario, para filtrar los usuarios por correo electrónico. Como la dirección de correo es única, es razonable que solo retorna la información de un usuario o de ninguno. Un ejemplo podría ser `/users?mobile=ADMIN&email=test@test.com`

- _**POST /users**_  permite crear un usuario. Vamos a utilizar la notación _**@RequestBody**_ para proporcionar el wrapper con la información del usuario, tal y como hacemos ahora. Como hay que saber el tipo de usuario a crear, en función del ROL, yo añadiría un atributo más en el wrapper, llamado _**role**_, en el que te indique el tipo de usuario a crear.

Como siempre, todos los endpoints retornan un código de respuesta HTTP 200, en caso de que la operación sea satisfactoria. En caso de que no sea así, deben retornar un wrapper con la información del error, tal y como están funcionando ahora.

Medita si quieres la ampliación que te propongo del wrapper, que me parece la solución más cómoda para gestionarlo. Si se te ocurre otra, cuéntame y lo hablamos. De igual forma, si hay algo que no quede, claro, me cuentas también ;-)

**Comment by fclopezjurado** [comment]
@EduardoFrancoGutierrez antes de que cierres el ticket!

Si consideras que el comentario que voy a hacer, es mejor colocarlo en otro ticket, lo realojamos.
Si echas un vistazo al método `updateUser` que tenemos en [UserResource](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/UserResource.java), preciso del ID del usuario para su edición.

En cambio, si observas los métodos `userList` o `userMobile`, todos ellos retornan una colección de instancias de [UserWrapper](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/wrappers/UserWrapper.java). Esta clase no dispone del atributo `id`, que luego será necesario.

Por otro lado, ya tenemos el wrapper [UserUpdateWrapper](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/wrappers/UserUpdateWrapper.java) que si que lo incluye, pero en cambio no incluye el atributo `active`.

Creo que deberíamos abrir otro ticket, para contemplar esta implementación, aparte del este ticket.

Avísame en cuanto lo leas, para confirmármelo y generamos otro ticket que contemple la problemática ;-)

**Comment by sergiobanegas** [comment]
@EduardoFrancoGutierrez 
Hola Eduardo, parece ser que has cambiado un recurso que un compañero hizo para servir a mi parte del front-end, en el que se encontraba a un usuario dado su móvil, bajo la URI **/users/{userMobile}**.

Lo has sustituido con la URI **/users/mobile?mobile=mobile?rol=rol**. Si no te importa me gustaría que al menos volvieses a poner el recurso que creo el compañero dejando el que has creado también, ya que  es necesario para mi parte y no necesito el rol para encontrarlo, haciendo más simple la URI.

¡Gracias de antemano!

**Comment by EduardoFrancoGutierrez** [comment]
@sergiobanegas  
Hola sergio, no sabiamos que estabas utilizando ahora mismo te restauro el recurso ;)

**Comment by EduardoFrancoGutierrez** [comment]
@sergiobanegas 
PD: si ves algo más que al refactorizar utilices en el front y lo haya quitado cuentamelo :)!!

**Comment by EduardoFrancoGutierrez** [comment]
@sergiobanegas
Buenas sergio he restaurado ya el recurso que comentabas , aun asi he pensado una solución que sirva para todos que es poner una api get de user  poniendo todos los parametros opcionales asi si quieres le pasas el mobil o la identificacion o el mail o el rol o todas ellas. Aun asi mañana lo esepecifico mejor y asi todo el mundo sabe como va :)

**Comment by sergiobanegas** [comment]
@EduardoFrancoGutierrez  ¡Genial gracias!.

Tengo constancia de lo que vas a hacer, que es realizar una búsqueda de usuarios para poder mostrarlos en el panel de administración. Ya me contó Fran la idea (y es muy buena), pero en mi opinión surgiría un conflicto ya que otra persona ya realizó el recurso y lo documentó.

Yo diría de dejarlo ya que este recurso es la típica obtención de recurso único **GET /URI/{parametro}**, mientras que el otro (aunque también pueda devolver un recurso único) esta más destinado a una búsqueda más flexible.
