### ISSUE TITLE
More API Resources for Tickets & Shoppings

### ISSUE THREAD

**Issue by fclopezjurado** [miw-upm/SPRING.tpv#59]
### Endpoins para la obtención de tickets y líneas de tickets (shoppings) 

- **_GET /tickets?mobile={mobile}_**: Endpoint que retorna una colección de tickets asociados a un usuario. Se proporciona un filtro al endpoint como **_@QueryParameter_**, con el número de móvil del usuario. Este endpoint debe estar paginado en el back-end, aunque también se implemente paginación en front-end.

Se recomienda, para mejoras en el rendimiento de las comunicaciones y evitar el envío de información innecesaria, el servidor back-end retorne solo retorna la referencia de cada ticket y su fecha de creación. A día 29/05/17, se ofrecen dos alternativas para implementar el wrapper de cada ticket, en orden de preferencia. La alternativa a elegir, la debatimos en el hilo del ticket.

- Refactorización de la clase [TicketWrapper](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/wrappers/TicketWrapper.java) para independizar la información del ticket, de la información correspondiente a las líneas del ticket. Se recomienda la utilización de un wrapper para un ticket y otro para una línea de ticket o _shopping_. Tras esta independencia, se pueden hacer otros wrappers, como por ejemplo **_TicketsWrapper_**, que retorne una colección de instancias de **_TicketWrapper_** y otro wrapper llamado **_ShoppingsWrapper_**, que retorne una colección de instancias de **_ShoppingWrapper_**.

- Creación de algunos nuevos wrappers que satisfagan la necesidad.

- Utilización de los wrappers existentes, enviando mayor cantidad de información de la que se necesita.

El endpoint solo puede ser usado por un usuario con credenciales de administración del sistema. No obstante, en el periodo de desarrollo y pruebas, no es necesario dicha restricción.

Como siempre, en caso de error, el servidor debe responder con un código HTTP de error y con un wrapper, tal y como está especificado en la clase [ErrorMessage](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/exceptions/ErrorMessage.java)

- **_GET /shopping?reference={reference}_**: Endpoint que retorna una colección de líneas de ticket o _shoppings_ asociados a un ticket. Se proporciona un filtro al endpoint como **_@QueryParameter_**, con la referencia del ticket del que se quieren obtener las líneas. Este endpoint debe estar paginado en el back-end, aunque también se implemente paginación en front-end.

Al igual que ocurre con el primer endpoint, el único wrapper implementado a día de hoy que puede satisfacer las necesidades es [TicketWrapper](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/wrappers/TicketWrapper.java). Se plantea el mismo problema que en el anterior endpoint con los wrappers.

El endpoint solo puede ser usado por un usuario con credenciales de administración del sistema. No obstante, en el periodo de desarrollo y pruebas, no es necesario dicha restricción.

Como siempre, en caso de error, el servidor debe responder con un código HTTP de error y con un wrapper, tal y como está especificado en la clase [ErrorMessage](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/api/exceptions/ErrorMessage.java)

Antes de la implementación, se ruega consultar sugerencias y decidir en común la mejor alternativa.

> Tiempo estimado: **5h**. Tiempo real: **3h**

[Wiki]()

**Comment by jacobocl** [comment]
Hola @fclopezjurado 
En cuanto al primero de los recursos que propones (**GET /tickets?mobile={mobile}**), me parece bien lo que has indicado y la forma más adecuada de devolver el resultado creo que sería crear un wrapper para ello, que contenga la referencia del ticket y la fecha de creación del mismo ya que no le veo mucha utilidad a refactorizar TicketWrapper, porque lo normal es que cuando obtienes un Ticket, quieras también las líneas de compra (_shopping_), ya que éstas son un componente sin el que un ticket no tiene sentido. Por lo tanto, creo que es más adecuado crear un wrapper para este caso, ya que supongo que el uso que se le dará en el front-end será el de mostrar una lista con las referencias y fechas de creación de los tickets de un usuario y, tras elegir uno, obtener los detalles del mismo (para lo que se usaría el segundo recurso indicado en esta issue).

En cuanto al segundo recurso (**GET /shopping?reference={reference}**), creo que no sería necesario crearlo, ya que existe el recurso **GET /tickets/{reference}**, que devuelve el ticket completo, con todas sus líneas de compra. El ahorro de información necesaria de crear un nuevo recurso sería mínimo, ya que únicamente se ahorrarían 4 campos cortos (id, referencia, fecha de creación y móvil del usuario); además, aunque este recurso no tiene paginación, no creo que sea necesaria, ya que, supongo que este software está pensado más bien para tiendas pequeñas, por lo que, en una compra normal, un usuario no va a comprar una gran cantidad de productos diferentes (como mucho unos 10-12 productos diferentes). Puede haber algún ticket puntual con muchas líneas de compra, pero no considero necesario crear un nuevo recurso solo por esos casos puntuales.

Un saludo.

**Comment by fclopezjurado** [comment]
Buenas noches @jacobocl!

Efectivamente estás en lo cierto con la utilidad del primer endpoint. Me parece bien lo que propones ;-)
Respecto al segundo endpoint, si no le ves utilidad, sin problema se utiliza [**GET /tickets/{reference}**](https://github.com/miw-upm/SPRING.tpv/wiki/Gesti%C3%B3n-y-seguimiento-de-tickets#obtenci%C3%B3n-de-tickets).

Al retornar este segundo endpoint más información de la necesaria, propuse las tres alternativas, para que al final se consensuara. Si te parece bien dejarlo así, sin problema tampoco.

Si te ves con ganas, te puedes asignar el ticket y le metemos mano ;-)

Con respecto a la adaptación con el front, seguimos utilizando mocks, así que cuando esté disponible, solo es utilizar la URI correcta y listo.

Vamos hablando!

**Comment by jacobocl** [comment]
Sí, realmente creo que puede usarse **GET /tickets/{reference}**, ya que aunque da más información de la necesaria, no es demasiada.

Perfecto, entonces pues me asigno y ticket lo implemento como hemos hablado 👍

**Comment by fclopezjurado** [comment]
Genial @jacobocl ! :-)

Tengo un comentario respecto a **_GET /tickets?mobile={mobile}_**. Si al final hacemos un wrapper nuevo para este endpoint, estoy observando una cosa. El formato con el que se retorna el atributo **_created_** en [TicketWrapper](https://github.com/miw-upm/SPRING.tpv/blob/develop/src/main/java/wrappers/TicketWrapper.java) me parece extraño. Envía fechas con el formato `yyyyMMdd`. Creo que en el nuevo wrapper, sería más fácil retornar la fecha en milisegundos, teniendo libertad luego en el front de formatearla al gusto.

Si te parece buena la idea, lo hacemos así. No obstante, tampoco hay problema ;-)

**Comment by jacobocl** [comment]
Me parece bien. Se enviaba en este formato porque en la issue en que lo creé ponía que se usase ese formato, pero vamos, lo envío en milisegundos en el nuevo wrapper, sin problema.

**Comment by jacobocl** [comment]
Ya está implementado, el recurso, en concreto es **GET /tickets?mobile={mobile}&size={size}&page={page}**, ya que, para permitir la paginación es necesario indicar el **tamaño de las páginas** y **el número de página** que se quiere obtener. La respuesta sería similar a esta:

```json
{
  "content": [
    {
      "reference": "WIZJ2HodFyQEyAHosSedYdJJc9w",
      "created": 1496268000000
    }
  ],
  "last": false,
  "totalElements": 3,
  "totalPages": 3,
  "size": 1,
  "number": 1,
  "sort": null,
  "numberOfElements": 1,
  "first": false
}
```

En **content** está la lista con los tickets correspondientes al número de teléfono y luego hay algunos atributos más de la página:

  * **last**: Si es o no la última página.
  * **totalElements**: El número total de tickets que hay para el móvil indicado.
  * **totalPages**: El número total de páginas que hay para el tamaño indicado.
  * **size**: El tamaño de las páginas.
  * **number**: Número de página.
  * **sort**: Atributos por lo que se ordenan los elementos. En teoría, en la petición puede ponerse otro parámetro, **sort**, en el que se indicaría el nombre del atributo de la entidad **ticket** por el que se quiere ordenar el resultado y si esa ordenación debería en sentido ascendente (asc) o descentente (desc). Por ejemplo, para obtener el resultado ordenado por fecha de creación del ticket en orden descendente sería así: `GET /tickets?mobile=666000002&size=1&page=1&sort=created,desc`. Si no se indica este atributo, el resultado vendrá en el orden en que esté en la base de datos, es decir, por fecha de creación en sentido ascendente.
  * **numberOfElements**: Número de tickets que hay en la página obtenida.
  * **first**: Si es o no la primera página.

Si le das el visto bueno, cierro la issue.

**Comment by fclopezjurado** [comment]
Por mi OK @jacobocl!

Integraré todos los endpoints que tenga, durante el próximo fin de semana, para intentar quitar el máximo número de mocks posibles. No obstante, si hay algún bug a medida que lo pruebe, no hay problema. Te lo reporto y lo vemos en todo caso para el siguiente hito ;-)
