### ISSUE TITLE
Add angular to java resources

### ISSUE THREAD

**Issue by sergiobanegas** [miw-upm/SPRING.tpv#79]
Modificar el pom.xml para que muestre la carpeta de angular en Java Resources.
PROBLEMA: compila todos los archivos de angular a la hora de lanzar el servidor

> Tiempo estimado: **10m**. Tiempo real: **10m**

[Wiki]()

**Comment by kikevillab** [comment]
Sergio he realizado un despliegue haciendo un build de angular en la carpeta web app
voy a meter el codigo y me dices si te valdria

**Comment by kikevillab** [comment]
#81 Esta ya generado el codigo de esa Issue

**Comment by sergiobanegas** [comment]
Todo correcto!
